// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __armoShowImage_hh__
#define __armoShowImage_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__

#ifndef __x86__
#define __x86__
#endif

//#ifndef _X86_
//#define _X86_
//#endif
#ifndef __WIN32__
#define __WIN32__
#endif

#define HAVE_STRUCT_TIMESPEC
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_armoShowImage
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_armoShowImage
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_armoShowImage
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



#ifndef __armoShowImage__
#define __armoShowImage__
class armoShowImage;
class _objref_armoShowImage;
class _impl_armoShowImage;

typedef _objref_armoShowImage* armoShowImage_ptr;
typedef armoShowImage_ptr armoShowImageRef;

class armoShowImage_Helper {
public:
  typedef armoShowImage_ptr _ptr_type;

  static _ptr_type _nil();
  static _CORBA_Boolean is_nil(_ptr_type);
  static void release(_ptr_type);
  static void duplicate(_ptr_type);
  static void marshalObjRef(_ptr_type, cdrStream&);
  static _ptr_type unmarshalObjRef(cdrStream&);
};

typedef _CORBA_ObjRef_Var<_objref_armoShowImage, armoShowImage_Helper> armoShowImage_var;
typedef _CORBA_ObjRef_OUT_arg<_objref_armoShowImage,armoShowImage_Helper > armoShowImage_out;

#endif

// interface armoShowImage
class armoShowImage {
public:
  // Declarations for this interface type.
  typedef armoShowImage_ptr _ptr_type;
  typedef armoShowImage_var _var_type;

  static _ptr_type _duplicate(_ptr_type);
  static _ptr_type _narrow(::CORBA::Object_ptr);
  static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
  
  static _ptr_type _nil();

  static inline void _marshalObjRef(_ptr_type, cdrStream&);

  static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
    omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
    if (o)
      return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
    else
      return _nil();
  }

  static inline _ptr_type _fromObjRef(omniObjRef* o) {
    if (o)
      return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
    else
      return _nil();
  }

  static _core_attr const char* _PD_repoId;

  // Other IDL defined within this scope.
  
};

class _objref_armoShowImage :
  public virtual ::CORBA::Object,
  public virtual omniObjRef
{
public:
  // IDL operations
  char* showImageByString(const char* mesg);

  // Constructors
  inline _objref_armoShowImage()  { _PR_setobj(0); }  // nil
  _objref_armoShowImage(omniIOR*, omniIdentity*);

protected:
  virtual ~_objref_armoShowImage();

  
private:
  virtual void* _ptrToObjRef(const char*);

  _objref_armoShowImage(const _objref_armoShowImage&);
  _objref_armoShowImage& operator = (const _objref_armoShowImage&);
  // not implemented

  friend class armoShowImage;
};

class _pof_armoShowImage : public _OMNI_NS(proxyObjectFactory) {
public:
  inline _pof_armoShowImage() : _OMNI_NS(proxyObjectFactory)(armoShowImage::_PD_repoId) {}
  virtual ~_pof_armoShowImage();

  virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
  virtual _CORBA_Boolean is_a(const char*) const;
};

class _impl_armoShowImage :
  public virtual omniServant
{
public:
  virtual ~_impl_armoShowImage();

  virtual char* showImageByString(const char* mesg) = 0;
  
public:  // Really protected, workaround for xlC
  virtual _CORBA_Boolean _dispatch(omniCallHandle&);

private:
  virtual void* _ptrToInterface(const char*);
  virtual const char* _mostDerivedRepoId();
  
};




class POA_armoShowImage :
  public virtual _impl_armoShowImage,
  public virtual ::PortableServer::ServantBase
{
public:
  virtual ~POA_armoShowImage();

  inline ::armoShowImage_ptr _this() {
    return (::armoShowImage_ptr) _do_this(::armoShowImage::_PD_repoId);
  }
};







#undef _core_attr
#undef _dyn_attr



inline void
armoShowImage::_marshalObjRef(::armoShowImage_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_armoShowImage
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_armoShowImage
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_armoShowImage
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_armoShowImage
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_armoShowImage
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_armoShowImage
#endif

#endif  // __armoShowImage_hh__

