// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.

#include "armoShowImage.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_2;



armoShowImage_ptr armoShowImage_Helper::_nil() {
  return ::armoShowImage::_nil();
}

::CORBA::Boolean armoShowImage_Helper::is_nil(::armoShowImage_ptr p) {
  return ::CORBA::is_nil(p);

}

void armoShowImage_Helper::release(::armoShowImage_ptr p) {
  ::CORBA::release(p);
}

void armoShowImage_Helper::marshalObjRef(::armoShowImage_ptr obj, cdrStream& s) {
  ::armoShowImage::_marshalObjRef(obj, s);
}

armoShowImage_ptr armoShowImage_Helper::unmarshalObjRef(cdrStream& s) {
  return ::armoShowImage::_unmarshalObjRef(s);
}

void armoShowImage_Helper::duplicate(::armoShowImage_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

armoShowImage_ptr
armoShowImage::_duplicate(::armoShowImage_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

armoShowImage_ptr
armoShowImage::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


armoShowImage_ptr
armoShowImage::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

armoShowImage_ptr
armoShowImage::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_armoShowImage _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_armoShowImage* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_armoShowImage;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* armoShowImage::_PD_repoId = "IDL:armoShowImage:1.0";


_objref_armoShowImage::~_objref_armoShowImage() {
  
}


_objref_armoShowImage::_objref_armoShowImage(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::armoShowImage::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
_objref_armoShowImage::_ptrToObjRef(const char* id)
{
  if (id == ::armoShowImage::_PD_repoId)
    return (::armoShowImage_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::armoShowImage::_PD_repoId))
    return (::armoShowImage_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for armoShowImage::showImageByString

// Proxy call descriptor class. Mangled signature:
//  _cstring_i_cstring
class _0RL_cd_3b0c149695dd2068_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_3b0c149695dd2068_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::String_var result;
};

void _0RL_cd_3b0c149695dd2068_00000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);

}

void _0RL_cd_3b0c149695dd2068_00000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();

}

void _0RL_cd_3b0c149695dd2068_00000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalString(result,0);

}

void _0RL_cd_3b0c149695dd2068_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalString(0);

}

const char* const _0RL_cd_3b0c149695dd2068_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_3b0c149695dd2068_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_3b0c149695dd2068_00000000* tcd = (_0RL_cd_3b0c149695dd2068_00000000*)cd;
  _impl_armoShowImage* impl = (_impl_armoShowImage*) svnt->_ptrToInterface(armoShowImage::_PD_repoId);
  tcd->result = impl->showImageByString(tcd->arg_0);


}

char* _objref_armoShowImage::showImageByString(const char* mesg)
{
  _0RL_cd_3b0c149695dd2068_00000000 _call_desc(_0RL_lcfn_3b0c149695dd2068_10000000, "showImageByString", 18);
  _call_desc.arg_0 = mesg;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}

_pof_armoShowImage::~_pof_armoShowImage() {}


omniObjRef*
_pof_armoShowImage::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::_objref_armoShowImage(ior, id);
}


::CORBA::Boolean
_pof_armoShowImage::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::armoShowImage::_PD_repoId))
    return 1;
  
  return 0;
}

const _pof_armoShowImage _the_pof_armoShowImage;

_impl_armoShowImage::~_impl_armoShowImage() {}


::CORBA::Boolean
_impl_armoShowImage::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "showImageByString")) {

    _0RL_cd_3b0c149695dd2068_00000000 _call_desc(_0RL_lcfn_3b0c149695dd2068_10000000, "showImageByString", 18, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
_impl_armoShowImage::_ptrToInterface(const char* id)
{
  if (id == ::armoShowImage::_PD_repoId)
    return (::_impl_armoShowImage*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::armoShowImage::_PD_repoId))
    return (::_impl_armoShowImage*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
_impl_armoShowImage::_mostDerivedRepoId()
{
  return ::armoShowImage::_PD_repoId;
}

POA_armoShowImage::~POA_armoShowImage() {}

